### ISSUE TITLE
Failed to install xap file

### ISSUE THREAD

**Issue by Arizumais1** [8212369/WPR#4]
![Screenshot_2022-09-26-18-16-55-827_com x8212369 WPR](https://user-images.githubusercontent.com/100060288/192714853-cc5fb944-1e6a-48c4-8d45-531be27dd0f5.jpg)
Failed to install xap file on Android
failed to install xap file #

**Comment by mediaexplorer74** [comment]
> Failed to install xap file on Android failed to install xap file #

Hi, I think that many xap files simply incompatible with WPR (secured or contained specific content?). 

I got/catched the same bug (when experimented with Desktop edition) as you when I tried Fruit_Ninja_v1.0.0.0.xap file... BUT I found another Fruit_Ninja_v1.1.0.0.xap (at Russian 4PDA.to site/forum), and at now all seems to be ok ;)

Also I discovered Telegram channel named "Lumia Apps". Some XAPs installed normally and even allow to start the mini-game :)

Do you tried that xap file at Windows Desktop (not Android) version of WPR app? How your xap file named? Please share (attach) it if You can ;)

Best wishes,
m.e.

**Comment by mediaexplorer74** [comment]
Anyone (anybody) found good xap file of legendary Flappy Bird microgame? =)
I searched anywhere. Epic fail =(
