### ISSUE TITLE
Failed to run Birds On A Wire game (and many many other xap games) at Android

### ISSUE THREAD

**Issue by mediaexplorer74** [8212369/WPR#7]
Hi! I noticed than Birds On A Wire game don't want to run at Android system... but I can start it via my forked WPR build at Windows system :

![image](https://user-images.githubusercontent.com/12032735/193136359-569d704b-b8a5-4bac-9d84-f9a6f09c6180.png)

**Comment by Arizumais1** [comment]
No games are running on Android version.

**Comment by mediaexplorer74** [comment]
The users detected that no games are running on Android version.. I's so strange. Today I cannot start the games that I installed yesterday... WPR for Android is only tech-demo... I cannot delete my installed apps. Perhaps, I cannot start any game more then once or two... (?)
Maybe, db structure damaged... or phone memory eshousted... i really don't know =( 
P.S. I deleted WPR 0.0.1-alpha from my Honor 7 and tried re-install it again... No effect: game run problems still here.

Ok, as bad C# developer and great explorer, I quickly R.E. WPR and did "dirty bug fixes".  Then I tried to deploy the WPR "forks" assembled by myself.. The result: no so big progress, many games runned with great bugs. :(

2 deys ago some user wrote here:
> Hi mediaexplorer74 your new builds v0.0.1-proto3 and v0.0.1-proto2 are not working on Android 10 ? 

I only can answer:
Idk what proto2/3 apk file/package failed to install... Maybe, your Android is not on developer mode... or it blocks unsafe app installing/setup ?... Idk, really. However, I reloaded WPR-proto2.apk and WPR-proto3.apk here: 
https://github.com/mediaexplorer74/WPR/releases/

Please notice, that it's only my experimental soft (as I truely noted at my fork's README). I have no any resources to support it. 
Really, make your own research and develop really stable WPR with good multi-platform support, if you are developer-like man. :)
How I "assembled" my apk files?  I only "grabbed" that apk files at the moment of succesful deploying WPR-proto on my old Honor 7c with old Android (8 or 8.1... i don't control the version) , and only shared on GitHub. 
That's all I did. I'm very poor specialist at "Avalonia multi-platforming", sorry.

Quick plan to your DIY:
- Install VS 2022 Preview
- Install Android 10 SDK
- Fork and clone my WPR repo
- Rebuild and deploy 
- Give feedback again

Best wishes and thanx for your WPR "testing",
 [m][e]

**Comment by Arizumais1** [comment]
Hi mediaexplorer74 your new builds v0.0.1-proto3 and v0.0.1-proto2 are not working on Android 10 ? 
![Screenshot_2022-10-02-11-27-41-509_com google android packageinstaller](https://user-images.githubusercontent.com/100060288/193448495-102d28d2-44d9-4e30-a7fb-1a1c54018c1d.jpg)

**Comment by mediaexplorer74** [comment]
> Hi mediaexplorer74 your new builds v0.0.1-proto3 and v0.0.1-proto2 are not working on Android 10 ? 
Hi. Idk what App failed to install... Maybe, your Android is not on developer mode... or it blocks unsafe app installing/setup... Idk, really. As I say at my fork's README/ it's only my exepimental soft. I have no any resources to support it.

**Comment by progameir2309** [comment]
As I Can See, There Are Great Quality And No Bugs At That Game On My PC (Also My Android Phone) Maybe Your PC Is The Problem?
